### ISSUE TITLE
Internals not found

### ISSUE THREAD

**Issue by Cortrah** [devinivy/hapipal-realworld-example-app#4]
Hi Devin,

Thanks so much for this project and the detailed write up about how it works. I'm hoping to use it to learn more about hapi and hapipal.

When I try to install it with just "npm install" and "npm start" I get an "internals not found" error.

Server started at http://localhost:3000
Debug: handler, error 
    Error: Not Found
    at internals.notFound (/Users/cortrah/WebstormProjects/hapipal-realworld-example-app/node_modules/glue/node_modules/hapi/lib/core.js:618:16)
    at module.exports.internals.Manager.execute (/Users/cortrah/WebstormProjects/hapipal-realworld-example-app/node_modules/glue/node_modules/hapi/lib/toolkit.js:35:106)
    at Object.internals.handler (/Users/cortrah/WebstormProjects/hapipal-realworld-example-app/node_modules/glue/node_modules/hapi/lib/handler.js:50:48)
    at exports.execute (/Users/cortrah/WebstormProjects/hapipal-realworld-example-app/node_modules/glue/node_modules/hapi/lib/handler.js:35:36)
    at Request._lifecycle (/Users/cortrah/WebstormProjects/hapipal-realworld-example-app/node_modules/glue/node_modules/hapi/lib/request.js:263:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Any thoughts on what's wrong or how I can fix it? Maybe a global dependency I need? 

Thanks for any help!

**Comment by devinivy** [comment]
Hi @Cortrah—thanks for the thanks!  I think you've installed everything just fine.  You're seeing the "not found" error because the API is in development mode and you went to a route that doesn't exist, probably `http://localhost:3000/`.  Try going to a route that does exist, such as `http://localhost:3000/api/tags`.  If you'd like to see a list of the routes that do exist, you can use the [hpal CLI](https://github.com/hapipal/hpal): simply run `npx hpal run debug:routes` in your terminal.

**Comment by Cortrah** [comment]
Ahh Sweet. That makes sense!

Thanks again. I'm looking forward to experimenting with this.

Say hi to paldo for me :D
